# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and deploy it to railway

name: Railway Deploy
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Use Node.js v17.3.0
      uses: actions/setup-node@v2
      with:
        node-version: v17.3.0
        cache: 'npm'
        
    - name: Create File With ENC_KEY
      uses: finnp/create-file-action@1.0.0
      env:
        FILE_NAME: "config/key"
        FILE_DATA: "${{ secrets.ENC_KEY }}"
        
    - name: Create File With CLIENT_SECRET
      uses: finnp/create-file-action@1.0.0
      env:
        FILE_NAME: "config/client_secrect"
        FILE_DATA: "${{ secrets.CLIENT_SECRET }}"
        
    - name: "Install All Dependencies via NPM"
      run: npm i
    
    - name: "Install RailwayCLI and Deploy to railway"
      run: npm i -g @railway/cli && railway up
      env: 
        RAILWAY_TOKEN: "${{ secrets.RAILWAY_TOKEN }}"
        
